# Generated by Django 3.2.4 on 2022-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=255)),
                ('submission_id', models.IntegerField(default=-1)),
                ('question_id', models.IntegerField(default=-1)),
                ('user_id', models.IntegerField(default=-1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField(default=-1)),
                ('user_id', models.IntegerField(default=-1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
